
-- =============================================================================
-- SEED DATA
-- =============================================================================

INSERT INTO continents (name) VALUES
                                  ('Africa'),
                                  ('Antarctica'),
                                  ('Asia'),
                                  ('Europe'),
                                  ('North America'),
                                  ('Oceania'),
                                  ('South America');

-- Africa (continent_id = 1)
INSERT INTO countries (name, continent_id, surface, population) VALUES
                                                                     ('Nigeria',                  1,  923768,  223800000),
                                                                     ('Ethiopia',                 1, 1104300,  128691000),
                                                                     ('Egypt',                    1, 1002450,  104258000),
                                                                     ('Democratic Republic of the Congo', 1, 2344858, 102262000),
                                                                     ('Tanzania',                 1,  945087,   65497000),
                                                                     ('Kenya',                    1,  580367,   55100000),
                                                                     ('South Africa',             1, 1221037,   60414000),
                                                                     ('Algeria',                  1, 2381741,   45606000),
                                                                     ('Sudan',                    1, 1886068,   46874000),
                                                                     ('Morocco',                  1,  710850,   37840000);

-- Antarctica (continent_id = 2)
INSERT INTO countries (name, continent_id, surface, population) VALUES
    ('French Southern Territories', 2, 439781, 140);

-- Asia (continent_id = 3)
INSERT INTO countries (name, continent_id, surface, population) VALUES
                                                                     ('China',                    3, 9596960, 1425671000),
                                                                     ('India',                    3, 3287590, 1428627000),
                                                                     ('Indonesia',                3, 1904569,  277534000),
                                                                     ('Pakistan',                 3,  881913,  231402000),
                                                                     ('Bangladesh',               3,  147570,  172954000),
                                                                     ('Japan',                    3,  377930,  123295000),
                                                                     ('Philippines',              3,  300000,  117337000),
                                                                     ('Vietnam',                  3,  331212,   98186000),
                                                                     ('Iran',                     3, 1648195,   87923000),
                                                                     ('Turkey',                   3,  783356,   85341000),
                                                                     ('Thailand',                 3,  513120,   71801000),
                                                                     ('Myanmar',                  3,  676578,   54410000),
                                                                     ('South Korea',              3,   99909,   51745000),
                                                                     ('Iraq',                     3,  438317,   42164000),
                                                                     ('Afghanistan',              3,  652230,   40754000),
                                                                     ('Saudi Arabia',             3, 2149690,   35950000),
                                                                     ('Uzbekistan',               3,  447400,   35300000),
                                                                     ('Malaysia',                 3,  329847,   33574000),
                                                                     ('Yemen',                    3,  527968,   33697000),
                                                                     ('Nepal',                    3,  147181,   30034000);

-- Europe (continent_id = 4)
INSERT INTO countries (name, continent_id, surface, population) VALUES
                                                                     ('Germany',                  4,  357114,   84270000),
                                                                     ('United Kingdom',           4,  242495,   67736000),
                                                                     ('France',                   4,  551695,   68521000),
                                                                     ('Italy',                    4,  301340,   59240000),
                                                                     ('Spain',                    4,  505990,   47422000),
                                                                     ('Poland',                   4,  312679,   38386000),
                                                                     ('Ukraine',                  4,  603550,   43531000),
                                                                     ('Romania',                  4,  238397,   19202000),
                                                                     ('Netherlands',              4,   41543,   17618000),
                                                                     ('Belgium',                  4,   30528,   11590000),
                                                                     ('Sweden',                   4,  450295,   10521000),
                                                                     ('Czech Republic',           4,   78867,   10827000),
                                                                     ('Greece',                   4,  131957,   10718000),
                                                                     ('Portugal',                 4,   92212,   10247000),
                                                                     ('Hungary',                  4,   93028,    9709000),
                                                                     ('Austria',                  4,   83871,    9042000),
                                                                     ('Switzerland',              4,   41285,    8793000),
                                                                     ('Bulgaria',                 4,  110879,    6448000),
                                                                     ('Finland',                  4,  338145,    5541000),
                                                                     ('Denmark',                  4,   42924,    5910000),
                                                                     ('Slovakia',                 4,   49035,    5794000),
                                                                     ('Norway',                   4,  385207,    5408000),
                                                                     ('Ireland',                  4,   70273,    5056000),
                                                                     ('Croatia',                  4,   56594,    4036000),
                                                                     ('Moldova',                  4,   33846,    2617000),
                                                                     ('Bosnia and Herzegovina',   4,   51197,    3270000),
                                                                     ('Albania',                  4,   28748,    2842000),
                                                                     ('Lithuania',                4,   65300,    2795000),
                                                                     ('North Macedonia',          4,   25713,    2080000),
                                                                     ('Slovenia',                 4,   20271,    2119000),
                                                                     ('Latvia',                   4,   64589,    1830000),
                                                                     ('Estonia',                  4,   45228,    1330000),
                                                                     ('Luxembourg',               4,    2586,     660000),
                                                                     ('Malta',                    4,     316,     520000),
                                                                     ('Iceland',                  4,  102775,     376000),
                                                                     ('Andorra',                  4,     468,      77543),
                                                                     ('Liechtenstein',            4,     160,      39055),
                                                                     ('San Marino',               4,      61,      33745),
                                                                     ('Monaco',                   4,       2,      39244),
                                                                     ('Vatican City',             4,       0.44,    800);

-- North America (continent_id = 5)
INSERT INTO countries (name, continent_id, surface, population) VALUES
                                                                     ('United States',            5, 9833517,  335893238),
                                                                     ('Mexico',                   5, 1964375,  128455567),
                                                                     ('Canada',                   5, 9984670,   38781292),
                                                                     ('Guatemala',                5,  108889,   17357108),
                                                                     ('Honduras',                 5,  112492,   10432860),
                                                                     ('Cuba',                     5,  109884,   11212191),
                                                                     ('Haiti',                    5,   27750,   11447569),
                                                                     ('Dominican Republic',       5,   48671,   11228821),
                                                                     ('El Salvador',              5,   21041,    6364943),
                                                                     ('Nicaragua',                5,  130370,    6850540),
                                                                     ('Costa Rica',               5,   51100,    5213374),
                                                                     ('Panama',                   5,   75417,    4351267),
                                                                     ('Jamaica',                  5,   10991,    2823713),
                                                                     ('Trinidad and Tobago',      5,    5130,    1534937),
                                                                     ('Belize',                   5,   22966,     412190),
                                                                     ('Bahamas',                  5,   13943,     412623),
                                                                     ('Barbados',                 5,     430,     281200),
                                                                     ('Greenland',                5, 2166086,      56367),
                                                                     ('Saint Lucia',              5,     616,     184100),
                                                                     ('Antigua and Barbuda',      5,     442,     102634);

-- Oceania (continent_id = 6)
INSERT INTO countries (name, continent_id, surface, population) VALUES
                                                                     ('Australia',                6, 7741220,   26439111),
                                                                     ('Papua New Guinea',         6,  462840,    9593498),
                                                                     ('New Zealand',              6,  270467,    5123000),
                                                                     ('Fiji',                     6,   18272,     935974),
                                                                     ('Solomon Islands',          6,   28896,     720000),
                                                                     ('Vanuatu',                  6,   12189,     332462),
                                                                     ('Samoa',                    6,    2842,     205557),
                                                                     ('Kiribati',                 6,     811,     123419),
                                                                     ('Tonga',                    6,     747,     104494),
                                                                     ('Micronesia',               6,     702,     115023);

-- South America (continent_id = 7)
INSERT INTO countries (name, continent_id, surface, population) VALUES
                                                                     ('Brazil',                   7, 8515767,  215313498),
                                                                     ('Colombia',                 7, 1141748,   52215503),
                                                                     ('Argentina',                7, 2780400,   45773884),
                                                                     ('Peru',                     7, 1285216,   33359418),
                                                                     ('Venezuela',                7,  916445,   28301696),
                                                                     ('Chile',                    7,  756102,   19629590),
                                                                     ('Ecuador',                  7,  283561,   18001000),
                                                                     ('Bolivia',                  7, 1098581,   12388571),
                                                                     ('Paraguay',                 7,  406752,    7359000),
                                                                     ('Uruguay',                  7,  176215,    3518552),
                                                                     ('Guyana',                   7,  214969,     790612),
                                                                     ('Suriname',                 7,  163820,     618040),
                                                                     ('French Guiana',            7,   86504,     281612);

-- -------------------------
-- People (60 records)
-- -------------------------
INSERT INTO people (first_name, last_name) VALUES
                                               ('Alice',    'Martin'),
                                               ('Bob',      'Smith'),
                                               ('Charlie',  'Brown'),
                                               ('Diana',    'Prince'),
                                               ('Ethan',    'Hunt'),
                                               ('Fiona',    'Green'),
                                               ('George',   'Washington'),
                                               ('Hannah',   'Lee'),
                                               ('Ivan',     'Petrov'),
                                               ('Julia',    'Roberts'),
                                               ('Kevin',    'Hart'),
                                               ('Laura',    'Palmer'),
                                               ('Michael',  'Jordan'),
                                               ('Nina',     'Simone'),
                                               ('Oscar',    'Wilde'),
                                               ('Paula',    'Abdul'),
                                               ('Quentin',  'Tarantino'),
                                               ('Rachel',   'Green'),
                                               ('Samuel',   'Adams'),
                                               ('Tina',     'Turner'),
                                               ('Ursula',   'Burns'),
                                               ('Victor',   'Hugo'),
                                               ('Wendy',    'Williams'),
                                               ('Xander',   'Cage'),
                                               ('Yara',     'Greyjoy'),
                                               ('Zoe',      'Clarke'),
                                               ('Alice',    'Cooper'),      -- same first name as person 1
                                               ('Bob',      'Dylan'),       -- same first name as person 2
                                               ('Charlie',  'Chaplin'),     -- same first name as person 3
                                               ('Diana',    'Ross'),        -- same first name as person 4
                                               ('Ana',      'Folau'),
                                               ('Frank',    'Sinatra'),
                                               ('Grace',    'Kelly'),
                                               ('Henry',    'Ford'),
                                               ('Irene',    'Adler'),
                                               ('Jack',     'Nicholson'),
                                               ('Karen',    'Page'),
                                               ('Leo',      'Messi'),
                                               ('Maria',    'Sharapova'),
                                               ('Nathan',   'Drake'),
                                               ('Olivia',   'Newton'),
                                               ('Peter',    'Parker'),
                                               ('Quinn',    'Hughes'),
                                               ('Rita',     'Ora'),
                                               ('Steve',    'Rogers'),
                                               ('Thomas',   'Edison'),
                                               ('Uma',      'Thurman'),
                                               ('Vera',     'Wang'),
                                               ('Will',     'Smith'),
                                               ('Xena',     'Warrior'),
                                               ('Yusuf',    'Islam'),
                                               ('Zara',     'Phillips'),
                                               ('Adam',     'Driver'),
                                               ('Betty',    'White'),
                                               ('Carl',     'Sagan'),
                                               ('Donna',    'Summer'),
                                               ('Edward',   'Norton'),
                                               ('Flora',    'Fox'),
                                               ('Gary',     'Oldman'),
                                               ('Helen',    'Hunt');        -- person 60, no citizenship (intentional)

-- -------------------------
-- Citizenships
-- (person 60 left without citizenship intentionally for query 5b)
-- -------------------------
INSERT INTO citizenships (person_id, country_id) VALUES
-- single citizenships
(1,  (SELECT id FROM countries WHERE name='France')),
(2,  (SELECT id FROM countries WHERE name='United Kingdom')),
(3,  (SELECT id FROM countries WHERE name='United States')),
(4,  (SELECT id FROM countries WHERE name='Germany')),
(5,  (SELECT id FROM countries WHERE name='Japan')),
(6,  (SELECT id FROM countries WHERE name='Brazil')),
(7,  (SELECT id FROM countries WHERE name='Canada')),
(8,  (SELECT id FROM countries WHERE name='Australia')),
(9,  (SELECT id FROM countries WHERE name='Bangladesh')),
(10, (SELECT id FROM countries WHERE name='Italy')),
(11, (SELECT id FROM countries WHERE name='Mexico')),
(12, (SELECT id FROM countries WHERE name='Spain')),
(13, (SELECT id FROM countries WHERE name='Nigeria')),
(14, (SELECT id FROM countries WHERE name='South Africa')),
(15, (SELECT id FROM countries WHERE name='India')),
(16, (SELECT id FROM countries WHERE name='China')),
(17, (SELECT id FROM countries WHERE name='Argentina')),
(18, (SELECT id FROM countries WHERE name='Colombia')),
(19, (SELECT id FROM countries WHERE name='Peru')),
(20, (SELECT id FROM countries WHERE name='Chile')),
(21, (SELECT id FROM countries WHERE name='Egypt')),
(22, (SELECT id FROM countries WHERE name='Morocco')),
(23, (SELECT id FROM countries WHERE name='Kenya')),
(24, (SELECT id FROM countries WHERE name='Ethiopia')),
(25, (SELECT id FROM countries WHERE name='Tanzania')),
(26, (SELECT id FROM countries WHERE name='Ukraine')),
(27, (SELECT id FROM countries WHERE name='Poland')),
(28, (SELECT id FROM countries WHERE name='Netherlands')),
(29, (SELECT id FROM countries WHERE name='Sweden')),
(30, (SELECT id FROM countries WHERE name='Norway')),
-- dual/triple citizenships
(31, (SELECT id FROM countries WHERE name='France')),
(31, (SELECT id FROM countries WHERE name='New Zealand')),
(32, (SELECT id FROM countries WHERE name='United States')),
(32, (SELECT id FROM countries WHERE name='Italy')),
(32, (SELECT id FROM countries WHERE name='Canada')),   -- triple
(33, (SELECT id FROM countries WHERE name='Germany')),
(33, (SELECT id FROM countries WHERE name='Austria')),
(34, (SELECT id FROM countries WHERE name='Japan')),
(34, (SELECT id FROM countries WHERE name='South Korea')),
(35, (SELECT id FROM countries WHERE name='Brazil')),
(35, (SELECT id FROM countries WHERE name='Portugal')),
(36, (SELECT id FROM countries WHERE name='Australia')),
(36, (SELECT id FROM countries WHERE name='United Kingdom')),
(36, (SELECT id FROM countries WHERE name='Ireland')),  -- triple
(37, (SELECT id FROM countries WHERE name='India')),
(37, (SELECT id FROM countries WHERE name='United Kingdom')),
(38, (SELECT id FROM countries WHERE name='Argentina')),
(38, (SELECT id FROM countries WHERE name='Spain')),
(39, (SELECT id FROM countries WHERE name='Mexico')),
(39, (SELECT id FROM countries WHERE name='Spain')),
(40, (SELECT id FROM countries WHERE name='Nigeria')),
(40, (SELECT id FROM countries WHERE name='United Kingdom')),
(41, (SELECT id FROM countries WHERE name='France')),
(41, (SELECT id FROM countries WHERE name='Belgium')),
(41, (SELECT id FROM countries WHERE name='Switzerland')),  -- triple
(42, (SELECT id FROM countries WHERE name='United States')),
(42, (SELECT id FROM countries WHERE name='Philippines')),
(43, (SELECT id FROM countries WHERE name='Canada')),
(43, (SELECT id FROM countries WHERE name='United Kingdom')),
(44, (SELECT id FROM countries WHERE name='Australia')),
(44, (SELECT id FROM countries WHERE name='New Zealand')),
(45, (SELECT id FROM countries WHERE name='Sweden')),
(45, (SELECT id FROM countries WHERE name='Denmark')),
(46, (SELECT id FROM countries WHERE name='Germany')),
(46, (SELECT id FROM countries WHERE name='Poland')),
(47, (SELECT id FROM countries WHERE name='Japan')),
(47, (SELECT id FROM countries WHERE name='United States')),
(48, (SELECT id FROM countries WHERE name='China')),
(48, (SELECT id FROM countries WHERE name='Malaysia')),
(49, (SELECT id FROM countries WHERE name='United States')),
(49, (SELECT id FROM countries WHERE name='Jamaica')),
(50, (SELECT id FROM countries WHERE name='Turkey')),
(50, (SELECT id FROM countries WHERE name='Germany')),
(51, (SELECT id FROM countries WHERE name='Indonesia')),
(51, (SELECT id FROM countries WHERE name='Netherlands')),
(52, (SELECT id FROM countries WHERE name='South Africa')),
(52, (SELECT id FROM countries WHERE name='United Kingdom')),
(53, (SELECT id FROM countries WHERE name='United States')),
(53, (SELECT id FROM countries WHERE name='Canada')),
(53, (SELECT id FROM countries WHERE name='United Kingdom')), -- triple
(54, (SELECT id FROM countries WHERE name='Kenya')),
(54, (SELECT id FROM countries WHERE name='France')),
(55, (SELECT id FROM countries WHERE name='Colombia')),
(55, (SELECT id FROM countries WHERE name='Spain')),
(56, (SELECT id FROM countries WHERE name='Egypt')),
(56, (SELECT id FROM countries WHERE name='France')),
(57, (SELECT id FROM countries WHERE name='Vietnam')),
(57, (SELECT id FROM countries WHERE name='France')),
(58, (SELECT id FROM countries WHERE name='Finland')),
(58, (SELECT id FROM countries WHERE name='Sweden')),
(59, (SELECT id FROM countries WHERE name='Brazil')),
(59, (SELECT id FROM countries WHERE name='Italy'));
-- person 60 (Helen Hunt) has NO citizenships intentionally
